### ISSUE TITLE
How work on Macbook

### ISSUE THREAD

**Issue by orlovich91** [Sorrow446/Yandex-Music-Downloader#1]
Hello! Please tell me how to run your application on a Macbook? And how to get a Yandex music token on a macbook?

**Comment by Sorrow446** [comment]
It's possible on Mac. I don't provide binaries for them because the cross-compiling for Mac isn't great. Could you message me over Discord or Telegram so I could guide you through it. I can help with the token as well.

**Comment by Sorrow446** [comment]
Solved via TG.
Rust has an easy PKG installer you can use on their site. Then you can CD into the script's folder and do `cargo build --release`. Might need to delete the "extract_token" folder first.
