### ISSUE TITLE
Support unsynced lyrics

### ISSUE THREAD

**Issue by llistochek** [Sorrow446/Yandex-Music-Downloader#11]
Not all tracks have synced lyrics. Unsynced lyrics can be embedded in:
- MP3: `USLT` tag. ([source](https://id3.org/id3v2.3.0#Unsychronised_lyrics.2Ftext_transcription))
- FLAC: `LYRICS` tag. ([source](https://cweiske.de/tagebuch/embedded-lyrics.htm#ogg))
- M4A: `@lyr` tag. ([source](https://exiftool.org/TagNames/QuickTime.html#ItemList))

**Comment by Sorrow446** [comment]
Implemented, will push to code later.
