### ISSUE TITLE
[BUG] Only first disk from multi-disk album is downloaded

### ISSUE THREAD

**Issue by llistochek** [Sorrow446/Yandex-Music-Downloader#12]
Try to download multi-disk album (e.g. https://music.yandex.ru/album/19235277).

## Expected behavior 
All tracks are downloaded with proper track/disk number tags.
## Actual behavior
Only tracks from the first disk are downloaded.

**Comment by Sorrow446** [comment]
Would you prefer folders for each disk or all tracks in the root folder?

**Comment by Sorrow446** [comment]
Done :).
