### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by VadBar13** [Sorrow446/Yandex-Music-Downloader#14]
In this version I can not download some playlists:

1. My favorite: https://music.yandex.ru/users/VadBar13/playlists/3 ("playlist is empty or not present in user's playlists")
2. One of my playlists: https://music.yandex.ru/users/VadBar13/playlists/1000 (reqwest::Error { kind: Decode, source: Error("missing field `genre`", line: 1, column: 9469) })
3. Playlists for me: https://music.yandex.ru/users/yamusic-daily/playlists/50117763 ("playlist is empty or not present in user's playlists")

Is it a chance to add support?

**Comment by Sorrow446** [comment]
Hey. Support's implemented for your own playlists only. The problem's that the genre metadata isn't in one of the tracks. I'll make it optional so it can deserialize it. As for your favourites, not sure what could be the problem, but will look at it. I can implement the pre-made playlists by Yandex as well.

**Comment by Sorrow446** [comment]
I cloned your playlist and the genre field was present in all tracks, weird. Have gone ahead and handled when it's not present anyway.
