### ISSUE TITLE
Error: missing field `lyricsInfo`

### ISSUE THREAD

**Issue by SoliaRdi** [Sorrow446/Yandex-Music-Downloader#17]
Hi. 
I have manually uploaded tracks in playlist and seems like they have slightly different structure so i get:
reqwest::Error { kind: Decode, source: Error("missing field `lyricsInfo`", line: 1, column: 282822) }

<details open>
<summary>JSON example of track object:</summary>
<pre>
{
   "id":"39180cb4-ee99-40bb-b70d-feba1e6a1b29",
   "originalIndex":180,
   "timestamp":"2022-09-03T01:01:56+00:00",
   "track":{
      "id":"39180cb4-ee99-40bb-b70d-feba1e6a1b29",
      "realId":"39180cb4-ee99-40bb-b70d-feba1e6a1b29",
      "matchedTrack":{
         "id":"50680176",
         "realId":"50680176",
         "title":"Sirens Over Paris",
         "available":false,
         "availableForPremiumUsers":false,
         "availableFullWithoutPermission":false,
         "availableForOptions":[
            
         ],
         "disclaimers":[
            
         ],
         "artists":[
            {
               "id":834368,
               "name":"Fytch",
               "various":false,
               "composer":false,
               "available":true,
               "cover":{
                  "type":"from-album-cover",
                  "uri":"avatars.yandex.net/get-music-content/2390047/e78afa77.a.9663872-1/%%",
                  "prefix":"e78afa77.a.9663872-1"
               },
               "genres":[
                  
               ],
               "disclaimers":[
                  
               ]
            }
         ],
         "albums":[
            
         ],
         "lyricsAvailable":true,
         "type":"music",
         "rememberPosition":false,
         "trackSharingFlag":"COVER_ONLY",
         "lyricsInfo":{
            "hasAvailableSyncLyrics":true,
            "hasAvailableTextLyrics":true
         },
         "trackSource":"OWN",
         "error":"no-rights"
      },
      "available":true,
      "canPublish":false,
      "state":"playable",
      "desiredVisibility":"private",
      "filename":"Fytch - Sirens Over Paris.mp3",
      "storageDir":"247309_u/18ff8a0e-6fa6-4ecf-8212-ce360e8bce83.1",
      "durationMs":186310,
      "coverUri":"avatars.yandex.net/get-music-content/119639/u.918932c4-800e-452f-894c-ee948067804a/%%",
      "title":"Sirens Over Paris",
      "artists":[
         {
            "id":"834368",
            "name":"Fytch"
         }
      ],
      "albums":[
         
      ],
      "metaData":{
         "number":1,
         "volume":1,
         "year":2016,
         "genre":"Electronic"
      },
      "ugcArtistName":"Fytch",
      "userInfo":{
         "uid":***,
         "login":"***",
         "displayName":"***",
         "fullName":"***"
      },
      "trackSource":"UGC"
   },
   "recent":false,
   "originalShuffleIndex":180
}
</pre>
</details>

**Comment by Sorrow446** [comment]
Probably won't implement support for user-uploaded tracks any time soon as it's a lot more work than it seems, sorry. There's this field as well:
```json
"metaData":{
    "album":"Ibiza Euphoria",
    "number":18,
    "volume":1,
    "year":1999,
    "version":"Dance Dept - TTVCD3078",
    "genre":"Electronic"
 },
 ```
 How does Yandex handle tracks with no album/track titles?

**Comment by SoliaRdi** [comment]
Can you at exclude them? So i can download everything else in playlist. 
Dowloading tracks that i already have not really needed :)

**Comment by Sorrow446** [comment]
Exactly lol. Possibly, hopefully there's a way without removing them all from your playlist. There might be a param, I'll let you know.

**Comment by SoliaRdi** [comment]
No clue how it's done in rust, never touched it, but you can do smth like optional fields when parse json. So when track.lyricsInfo==nil continue. Could be more fields that should become optional.

**Comment by Sorrow446** [comment]
I meant the params to the API endpoint call, but yeah, Rust does have an optional type. It's more than just the lyrics unfortunately. If there's even just one user-uploaded track in the playlist, the whole structure changes. I'll see if the API accepts a param to not include them.

**Comment by Sorrow446** [comment]
Here you go. https://workupload.com/file/AFg2943m4rk

**Comment by SoliaRdi** [comment]
Worked perfectly, thank you🥳
