### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VictorK1963** [Sorrow446/Yandex-Music-Downloader#19]
config.toml
format = 4
keep_covers = true
out_path = "G:\Music"
token = "y0_AgxxxxxxxxxxxxxxXXXEXjx_2AABDqCApVzSLNS8NhquQ"
sleep = false
write_covers = true
get_original_covers = false
write_lyrics = true

the token has been changed. if you need a real token, write. The token has been pulled out extract_token.exe . The collection is mine.

Command CMD:
ym-dl.exe -u https://music.yandex.ru/users/VictorK1963@yandex.ru/playlists/3
or
ym-dl.exe -u https://music.yandex.ru/users/VictorK1963/playlists/3

Final:
D:\Music>ym-dl.exe -u https://music.yandex.ru/users/VictorK1963@yandex.ru/playlists/3
thread 'main' panicked at src/main.rs:623:10:
failed to parse args/config: Error { inner: Error { inner: TomlError { message: "invalid escape sequence\nexpected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\\`, `\"`", raw: Some("format = 4\r\nkeep_covers = true\r\nout_path = \"G:\\Music\"\r\ntoken = \"y0_AgxxxxxxxxxxxxxxxxAAEXjx_2A6ICApVzSLNS8NhquQ\"\r\nsleep = false\r\nwrite_covers = true\r\nget_original_covers = false\r\nwrite_lyrics = true"), keys: [], span: Some(48..49) } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

D:\Music>ym-dl.exe -u https://music.yandex.ru/users/VictorK1963/playlists/3
thread 'main' panicked at src/main.rs:623:10:
failed to parse args/config: Error { inner: Error { inner: TomlError { message: "invalid escape sequence\nexpected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\\`, `\"`", raw: Some("format = 4\r\nkeep_covers = true\r\nout_path = \"G:\\Music\"\r\ntoken = \"y0_Agxxxxxxxxxxxxxxxxxxxxxxjx_2AABApVzSLNS8NhquQ\"\r\nsleep = false\r\nwrite_covers = true\r\nget_original_covers = false\r\nwrite_lyrics = true"), keys: [], span: Some(48..49) } } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by VictorK1963** [comment]
Thanks, I'll try.

8 ноября 2024 г. 18:33:09 GMT+03:00, Sorrow446 ***@***.***> пишет:

**Comment by VictorK1963** [comment]
Now another mistake

C:\Users\Victor1963\Downloads\Yandex>ym-dl.exe -u https://music.yandex.ru/users/VictorK1963@yandex.ru/playlists/3
Signed in successfully.

URL 1 of 1:
URL failed.
reqwest::Error { kind: Decode, source: Error("missing field `coverUri`", line: 1, column: 951630) }

**Comment by Sorrow446** [comment]
Because the binaries are outdated.

Up-to-date with source code:
https://workupload.com/file/S9wkQ6uZZSp

**Comment by VictorK1963** [comment]
thank you very much! It's working!

**Comment by VictorK1963** [comment]
Good afternoon. Again it doesn't work, the option that:
Because the binaries are outdated.
Up-to-date with source code:
https://workupload.com/file/S9wkQ6uZZSp
 
it doesn't work anymore. The same thing doesn't work from the v0.1.7 site.
 
d:\Music>ym-dl.exe -u ***@***.***/playlists/3
Signed in successfully.
 
URL 1 of 1:
URL failed.
reqwest::Error { kind: Decode, source: Error("missing field `coverUri`", line: 1, column: 1392853) }
 
Help! Thank you.
