### ISSUE TITLE
README: "Sniff the Yandex Music app", please add how. By Wireshark?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Sorrow446/Yandex-Music-Downloader#4]

**Comment by Sorrow446** [comment]
Depends which you mean.

For Android, you need a rooted device with something like HTTPCanary.
For the Windows Yandex app, use the token extractor. https://github.com/Sorrow446/Yandex-Music-Downloader/releases/download/v0.1.0/extract_token.exe

If you can't do any of these for whatever reason, send me your credentials via Telegram and I'll do it for you.

**Comment by Sorrow446** [comment]
Here's the token extractor with Linux support that works with [cucumber's Linux Yandex Music client](https://github.com/cucumber-sp/yandex-music-linux)

https://gofile.io/d/Cus7by
