### ISSUE TITLE
`./ym-dl_amd64`: `thread 'main' panicked at src/main.rs:561:10`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Sorrow446/Yandex-Music-Downloader#5]
$ ./ym-dl_amd64 
thread 'main' panicked at src/main.rs:561:10:
failed to parse args/config: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/Yandex-Music-Downloader/blob/main/config.toml
